# Generated by Django 4.1.2 on 2022-10-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0004_bankdetail_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('gst_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('msme_certified', models.BooleanField(default=False)),
                ('msme_certificate', models.FileField(upload_to='')),
                ('bank_details', models.ManyToManyField(related_name='vendors', to='UserApp.bankdetail')),
                ('category', models.ManyToManyField(related_name='vendors', to='VendorApp.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_vendors', to='UserApp.info')),
                ('payment_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyclic_vendors', to='UserApp.info')),
            ],
        ),
    ]
