# Generated by Django 4.1.2 on 2022-11-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_remove_vendor_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='msme_certificate',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
