# Generated by Django 4.1.2 on 2022-11-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_bankdetail_vendor'),
        ('VendorApp', '0003_alter_vendor_gst_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('gst_number', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('msme_certified', models.BooleanField(default=False)),
                ('msme_certificate', models.FileField(blank=True, default='', upload_to='')),
                ('category', models.ManyToManyField(related_name='vendors_temp', to='VendorApp.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_vendors_temp', to='UserApp.info')),
                ('payment_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyclic_vendors_temp', to='UserApp.info')),
            ],
        ),
    ]
