# Generated by Django 4.1.2 on 2022-11-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0003_alter_contract_vendor_alter_purchase_vendor'),
        ('UserApp', '0006_alter_bankdetail_vendor'),
        ('VendorApp', '0004_vendortemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
