# Generated by Django 4.1.2 on 2022-11-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_bankdetail_vendor'),
        ('VendorApp', '0006_rename_vendortemp_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(related_name='vendors', to='VendorApp.category'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_vendors', to='UserApp.info'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyclic_vendors', to='UserApp.info'),
        ),
    ]
