# Generated by Django 4.1.2 on 2022-12-16 06:45

import VendorApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0008_alter_vendor_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='msme_certificate',
            field=models.FileField(blank=True, default='', upload_to=VendorApp.models.upload_msme_certificate),
        ),
    ]
