# Generated by Django 4.1.2 on 2022-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0010_bankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(max_length=20),
        ),
    ]
