# Generated by Django 4.1.2 on 2022-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
