# Generated by Django 4.1.2 on 2022-10-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_role_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.role'),
        ),
    ]
