# Generated by Django 4.1.2 on 2022-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('acc_name', models.CharField(max_length=40)),
                ('acc_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('ifsc', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=40)),
                ('bank_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
    ]
