# Generated by Django 4.1.2 on 2022-11-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_remove_vendor_bank_details'),
        ('UserApp', '0004_bankdetail_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='vendor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='VendorApp.vendor'),
        ),
    ]
