# Generated by Django 4.1.2 on 2022-12-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_bankdetail_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDetail',
        ),
    ]
