# Generated by Django 4.1.2 on 2022-10-27 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(max_length=20)),
                ('inv_date', models.DateField()),
                ('inv_number', models.CharField(max_length=20)),
                ('inv_amount', models.CharField(max_length=9)),
                ('invoice', models.FileField(upload_to='')),
                ('gst_perc', models.FloatField(default=0.0)),
                ('remarks', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.CharField(max_length=9)),
                ('payment_remarks', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.category')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('remarks', models.TextField()),
                ('contract', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.vendor')),
            ],
        ),
    ]
