# Generated by Django 4.1.2 on 2022-11-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0004_vendortemp'),
        ('PurchaseApp', '0002_purchase_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.vendortemp'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.vendortemp'),
        ),
    ]
