# Generated by Django 4.1.2 on 2022-12-29 21:50

import PurchaseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0003_alter_contract_vendor_alter_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.FileField(blank=True, default='', upload_to=PurchaseApp.models.upload_contract),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice',
            field=models.FileField(blank=True, default='', upload_to=PurchaseApp.models.upload_invoice),
        ),
    ]
