# Generated by Django 4.1.2 on 2022-12-31 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0011_alter_bankdetail_ifsc'),
        ('PurchaseApp', '0004_alter_contract_contract_alter_contract_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VendorApp.bankdetail'),
        ),
    ]
