# Generated by Django 4.1.2 on 2022-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0005_purchase_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
